DATA: 'test1spec.fits'    # File name of processed image (raw-sky)/flat for IR, (raw-bias)/flat for optical
VAR: None     # Variance image of data in DN^2 (i.e., data/q+rn^2)
RN: 0.0      # Read noise of data frame in DN
Q: 10.0       # Effective number of photos per DN for data frame
X1: 256      # Start boundary in x of spectrum (inclusive)
X2: 512      # End Boundary in x of spectrum (inclusive)

OPTIONS:
  INPUT:
    # GENERAL
    SKYVAR: None      # Variance image of sky (default 0s)
    INMASK: None      # User input mask with good pixels=1, bad=0 (default 1s)
    BPCT: None        # Set the percentage of bad pixels before kicking out (0.5)
    INTEGRATE: None   # Set to integrate over bad pixels when calculating spec for use in the profile fitting

    # BACKGROUND FITTING
    NOBGFIT: None     # Set to not fit the background
    BTHRESH: None     # sigma threshold for cosmic ray rejection for bg, (3)
    BGDEG: None       # degree of polynomial fit for interpolation in fitbg (1)

    # PROFILE FITTING - GEOMETRY ADJUSTMENT
    ADJFUNC: None     # The name of the function to call with images to modify
    ADJOPTIONS:
      LEVEL: None     # The amount to expand the array
      CENTER: None    # Set to 1 to adjust each column so the centers line up (1)
      WIDTH: None     # Adjust to reflect each pixel's relative distance from center
                      # according to that row's gaussian width
      CENTROID: None  # Set to use centroid fitting instead
      GAUSSTH: None   # The absolute value of allowable error when fitting a gaussian
                      # to the data (3 percent)
      SHIFTTH: None   # The absolute allowable error between a row's center and the
                      # fitted trace
      DEGCONTR: None  # degree of fit to use when contracting the array (2)
      CENTERDEG: None # degree of fit for estimating the shift (2)
      CENTERFIT: None # set to not fit the estimated centers and not accept the
                      # the fitting to be correct

    ADJPARMS:
      ORIGX: None
      ADJX: None
      TRACEEST: None
      WIDTHEST: None

    # PROFILE FITTING - SMOOTHING
    NOPROFFIT: None
    PTHRESH: None
    PROFDEG: None
    FITGAUSS: None
    FITBOXCAR: None
    BOXCARHW: None

    # OPTIMAL EXTRACTION
    ETHRESH: None

    # DEBUGGING
    VERBOSE: None
      # Set to level of output
      #   0 - fatal
      #   1 - collect stats
      #   2 - where you are in the program
      #   3 - output every warning
      #   4 - plot how the data are being used
      #   5 - stop after each iteration
    PLOTTYPE: None
      # Set to the type of plot output to the screen
      #   0 - No Plots
      #   1 - Show a summary of all processed frames
      #   2 - Show the data used as input to procvect
      #   3 - Show how procvect is fitting the data
      #   4 - Use shade_surf to show the fitted and raw data
      #   5 - Show all plots
    BGOTOVECT: None
    PGOTOVECT: None
    EGOTOVECT: None
    DEBUGHEAD: None
  OUTPUT:
    # Background Fitting
    BGIM: None      # Interpolated sky background image
    BGMASK: None    # Background's mask
    BGRES: None     # The sigma difference between the actual and expected
    BERRVECT: None  # Mask of rows where iteration stopped during fitbg

    # Standard Extraction
    STDSPEC: None   # Standard spectrum
    STDVAR: None    # Returns variance of standard spectrum

    # Profile Fitting:
    PROFIM: None    # Calculated profile image
    PROFMASK: None  # The calculated profile cosmic ray mask
    DIFPMASK: None  # Pixels rejected during the profile fitting routine
    PROFRES: None   # The profile residual image
    PERRVECT: None  # Mask of rows/columns where iteration stopped during fitprof

    # Optimal Extraction:
    OPVAR: None     # Returns optimally extracted variance
    VAROUT: None    # Returns the final calculated variance
    EXMASK: None    # Calculated cosmic ray mask
    EXRES: None     # Cosmic ray image: dataim-spec*profim*profim/varim
    EERRVECT: None  # Mask of rows where iteration stopped during extrspec