@startuml
'https://plantuml.com/class-diagram

interface fitbg_parameters{
+data
+x1
+x2
+bgdeg
+q_val
+v0
+inmask
+varim
+bthresh
+bgres
+errvect
+bgmask
+skyvar
+verbose
+nobgfit
+gotovect
+bpct
+plottype
}

interface procvect_parameters{
+datav
+varv
+maskv
+crv
+thresh
+xvals
+errflag
+q_val
+v0
+skyvarv
+verbose
+vectnum
+func
+parm
+bpct
+plottype
}

class optspecextr {
--Calls--
fitbg()
stdexr()
fitprof()
extrspec()
summaryopt()
}

class fitbg {
--Calls--
procvect()
}


optspecextr::fitbg -right-> fitbg_parameters
fitbg_parameters -right-> fitbg
fitbg -right-> procvect_parameters
procvect_parameters -right-> procvect

@enduml